export const SHOW_ALL = 'SHOW_ALL'
export const SET_BLOCK = 'SET_BLOCK'
export const ADD_SUB_BLOCK = 'ADD_SUB_BLOCK'
export const REMOVE_SUB_BLOCK = 'REMOVE_SUB_BLOCK'
export const TOGGLE_PREW_SHOW = 'TOGGLE_PREW_SHOW'